//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.10 at 09:54:16 PM CDT 
//


package xsdToJava.com.gmc.xsdToJava;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the xsdToJava.com.gmc.xsdToJava package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xsdToJava.com.gmc.xsdToJava
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Report.Tablix5 .Textbox70 .Textbox28 }
     * 
     */
    public Report.Tablix5 .Textbox70 .Textbox28 createReportTablix5Textbox70Textbox28() {
        return new Report.Tablix5 .Textbox70 .Textbox28();
    }

    /**
     * Create an instance of {@link Report.Tablix5 .WardNameCollection.WardName.Street1Collection }
     * 
     */
    public Report.Tablix5 .WardNameCollection.WardName.Street1Collection createReportTablix5WardNameCollectionWardNameStreet1Collection() {
        return new Report.Tablix5 .WardNameCollection.WardName.Street1Collection();
    }

    /**
     * Create an instance of {@link Report.Tablix5 .Textbox70 .Textbox28 .Textbox48 .Textbox120 .Textbox56 .Textbox145 }
     * 
     */
    public Report.Tablix5 .Textbox70 .Textbox28 .Textbox48 .Textbox120 .Textbox56 .Textbox145 createReportTablix5Textbox70Textbox28Textbox48Textbox120Textbox56Textbox145() {
        return new Report.Tablix5 .Textbox70 .Textbox28 .Textbox48 .Textbox120 .Textbox56 .Textbox145();
    }

    /**
     * Create an instance of {@link Report.Tablix5 .Textbox70 }
     * 
     */
    public Report.Tablix5 .Textbox70 createReportTablix5Textbox70() {
        return new Report.Tablix5 .Textbox70();
    }

    /**
     * Create an instance of {@link Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2 .Textbox172 }
     * 
     */
    public Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2 .Textbox172 createReportTablix5WardNameCollectionWardNameStreet1CollectionStreet1BalanceTax2Textbox172() {
        return new Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2 .Textbox172();
    }

    /**
     * Create an instance of {@link Report }
     * 
     */
    public Report createReport() {
        return new Report();
    }

    /**
     * Create an instance of {@link Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2 .AssesmentNoCollection.AssesmentNo }
     * 
     */
    public Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2 .AssesmentNoCollection.AssesmentNo createReportTablix5WardNameCollectionWardNameStreet1CollectionStreet1BalanceTax2AssesmentNoCollectionAssesmentNo() {
        return new Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2 .AssesmentNoCollection.AssesmentNo();
    }

    /**
     * Create an instance of {@link Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2 .AssesmentNoCollection.AssesmentNo.WUConnectionNo.OwnerFName }
     * 
     */
    public Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2 .AssesmentNoCollection.AssesmentNo.WUConnectionNo.OwnerFName createReportTablix5WardNameCollectionWardNameStreet1CollectionStreet1BalanceTax2AssesmentNoCollectionAssesmentNoWUConnectionNoOwnerFName() {
        return new Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2 .AssesmentNoCollection.AssesmentNo.WUConnectionNo.OwnerFName();
    }

    /**
     * Create an instance of {@link Report.Tablix5 .Textbox70 .Textbox28 .Textbox48 .Textbox120 .Textbox56 .Textbox145 .InstallmentNameCollection }
     * 
     */
    public Report.Tablix5 .Textbox70 .Textbox28 .Textbox48 .Textbox120 .Textbox56 .Textbox145 .InstallmentNameCollection createReportTablix5Textbox70Textbox28Textbox48Textbox120Textbox56Textbox145InstallmentNameCollection() {
        return new Report.Tablix5 .Textbox70 .Textbox28 .Textbox48 .Textbox120 .Textbox56 .Textbox145 .InstallmentNameCollection();
    }

    /**
     * Create an instance of {@link Report.Tablix5 .WardNameCollection.WardName.Textbox180 .Textbox181 }
     * 
     */
    public Report.Tablix5 .WardNameCollection.WardName.Textbox180 .Textbox181 createReportTablix5WardNameCollectionWardNameTextbox180Textbox181() {
        return new Report.Tablix5 .WardNameCollection.WardName.Textbox180 .Textbox181();
    }

    /**
     * Create an instance of {@link Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2 .AssesmentNoCollection.AssesmentNo.WUConnectionNo.OwnerFName.NewDoorNo.Textbox145 }
     * 
     */
    public Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2 .AssesmentNoCollection.AssesmentNo.WUConnectionNo.OwnerFName.NewDoorNo.Textbox145 createReportTablix5WardNameCollectionWardNameStreet1CollectionStreet1BalanceTax2AssesmentNoCollectionAssesmentNoWUConnectionNoOwnerFNameNewDoorNoTextbox145() {
        return new Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2 .AssesmentNoCollection.AssesmentNo.WUConnectionNo.OwnerFName.NewDoorNo.Textbox145();
    }

    /**
     * Create an instance of {@link Report.Tablix5 .Textbox70 .Textbox28 .Textbox48 }
     * 
     */
    public Report.Tablix5 .Textbox70 .Textbox28 .Textbox48 createReportTablix5Textbox70Textbox28Textbox48() {
        return new Report.Tablix5 .Textbox70 .Textbox28 .Textbox48();
    }

    /**
     * Create an instance of {@link Report.Tablix5 .Textbox70 .Textbox28 .Textbox48 .Textbox120 }
     * 
     */
    public Report.Tablix5 .Textbox70 .Textbox28 .Textbox48 .Textbox120 createReportTablix5Textbox70Textbox28Textbox48Textbox120() {
        return new Report.Tablix5 .Textbox70 .Textbox28 .Textbox48 .Textbox120();
    }

    /**
     * Create an instance of {@link Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2 .AssesmentNoCollection.AssesmentNo.WUConnectionNo.OwnerFName.NewDoorNo.Textbox146 }
     * 
     */
    public Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2 .AssesmentNoCollection.AssesmentNo.WUConnectionNo.OwnerFName.NewDoorNo.Textbox146 createReportTablix5WardNameCollectionWardNameStreet1CollectionStreet1BalanceTax2AssesmentNoCollectionAssesmentNoWUConnectionNoOwnerFNameNewDoorNoTextbox146() {
        return new Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2 .AssesmentNoCollection.AssesmentNo.WUConnectionNo.OwnerFName.NewDoorNo.Textbox146();
    }

    /**
     * Create an instance of {@link Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2 .Textbox172 .Textbox145 .InstallmentNameCollection }
     * 
     */
    public Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2 .Textbox172 .Textbox145 .InstallmentNameCollection createReportTablix5WardNameCollectionWardNameStreet1CollectionStreet1BalanceTax2Textbox172Textbox145InstallmentNameCollection() {
        return new Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2 .Textbox172 .Textbox145 .InstallmentNameCollection();
    }

    /**
     * Create an instance of {@link Report.Tablix5 .WardNameCollection }
     * 
     */
    public Report.Tablix5 .WardNameCollection createReportTablix5WardNameCollection() {
        return new Report.Tablix5 .WardNameCollection();
    }

    /**
     * Create an instance of {@link Report.Tablix5 .WardNameCollection.WardName.Textbox180 .Textbox181 .Textbox145 .InstallmentNameCollection.InstallmentName }
     * 
     */
    public Report.Tablix5 .WardNameCollection.WardName.Textbox180 .Textbox181 .Textbox145 .InstallmentNameCollection.InstallmentName createReportTablix5WardNameCollectionWardNameTextbox180Textbox181Textbox145InstallmentNameCollectionInstallmentName() {
        return new Report.Tablix5 .WardNameCollection.WardName.Textbox180 .Textbox181 .Textbox145 .InstallmentNameCollection.InstallmentName();
    }

    /**
     * Create an instance of {@link Report.Tablix5 .WardNameCollection.WardName.Textbox180 .Textbox181 .Textbox145 }
     * 
     */
    public Report.Tablix5 .WardNameCollection.WardName.Textbox180 .Textbox181 .Textbox145 createReportTablix5WardNameCollectionWardNameTextbox180Textbox181Textbox145() {
        return new Report.Tablix5 .WardNameCollection.WardName.Textbox180 .Textbox181 .Textbox145();
    }

    /**
     * Create an instance of {@link Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2 }
     * 
     */
    public Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2 createReportTablix5WardNameCollectionWardNameStreet1CollectionStreet1BalanceTax2() {
        return new Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2();
    }

    /**
     * Create an instance of {@link Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 }
     * 
     */
    public Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 createReportTablix5WardNameCollectionWardNameStreet1CollectionStreet1() {
        return new Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1();
    }

    /**
     * Create an instance of {@link Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2 .Textbox172 .Textbox146 }
     * 
     */
    public Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2 .Textbox172 .Textbox146 createReportTablix5WardNameCollectionWardNameStreet1CollectionStreet1BalanceTax2Textbox172Textbox146() {
        return new Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2 .Textbox172 .Textbox146();
    }

    /**
     * Create an instance of {@link Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2 .Textbox172 .Textbox145 }
     * 
     */
    public Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2 .Textbox172 .Textbox145 createReportTablix5WardNameCollectionWardNameStreet1CollectionStreet1BalanceTax2Textbox172Textbox145() {
        return new Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2 .Textbox172 .Textbox145();
    }

    /**
     * Create an instance of {@link Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .Textbox115 }
     * 
     */
    public Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .Textbox115 createReportTablix5WardNameCollectionWardNameStreet1CollectionStreet1Textbox115() {
        return new Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .Textbox115();
    }

    /**
     * Create an instance of {@link Report.Tablix5 .WardNameCollection.WardName.Textbox180 .Textbox181 .Textbox145 .InstallmentNameCollection }
     * 
     */
    public Report.Tablix5 .WardNameCollection.WardName.Textbox180 .Textbox181 .Textbox145 .InstallmentNameCollection createReportTablix5WardNameCollectionWardNameTextbox180Textbox181Textbox145InstallmentNameCollection() {
        return new Report.Tablix5 .WardNameCollection.WardName.Textbox180 .Textbox181 .Textbox145 .InstallmentNameCollection();
    }

    /**
     * Create an instance of {@link Report.Tablix5 .WardNameCollection.WardName.Textbox114 }
     * 
     */
    public Report.Tablix5 .WardNameCollection.WardName.Textbox114 createReportTablix5WardNameCollectionWardNameTextbox114() {
        return new Report.Tablix5 .WardNameCollection.WardName.Textbox114();
    }

    /**
     * Create an instance of {@link Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2 .Textbox172 .Textbox145 .InstallmentNameCollection.InstallmentName }
     * 
     */
    public Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2 .Textbox172 .Textbox145 .InstallmentNameCollection.InstallmentName createReportTablix5WardNameCollectionWardNameStreet1CollectionStreet1BalanceTax2Textbox172Textbox145InstallmentNameCollectionInstallmentName() {
        return new Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2 .Textbox172 .Textbox145 .InstallmentNameCollection.InstallmentName();
    }

    /**
     * Create an instance of {@link Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2 .AssesmentNoCollection.AssesmentNo.WUConnectionNo }
     * 
     */
    public Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2 .AssesmentNoCollection.AssesmentNo.WUConnectionNo createReportTablix5WardNameCollectionWardNameStreet1CollectionStreet1BalanceTax2AssesmentNoCollectionAssesmentNoWUConnectionNo() {
        return new Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2 .AssesmentNoCollection.AssesmentNo.WUConnectionNo();
    }

    /**
     * Create an instance of {@link Report.Tablix5 .WardNameCollection.WardName.Textbox114 .Textbox145 .InstallmentNameCollection }
     * 
     */
    public Report.Tablix5 .WardNameCollection.WardName.Textbox114 .Textbox145 .InstallmentNameCollection createReportTablix5WardNameCollectionWardNameTextbox114Textbox145InstallmentNameCollection() {
        return new Report.Tablix5 .WardNameCollection.WardName.Textbox114 .Textbox145 .InstallmentNameCollection();
    }

    /**
     * Create an instance of {@link Report.Tablix5 .Textbox70 .Textbox28 .Textbox48 .Textbox120 .Textbox56 .Textbox145 .InstallmentNameCollection.InstallmentName }
     * 
     */
    public Report.Tablix5 .Textbox70 .Textbox28 .Textbox48 .Textbox120 .Textbox56 .Textbox145 .InstallmentNameCollection.InstallmentName createReportTablix5Textbox70Textbox28Textbox48Textbox120Textbox56Textbox145InstallmentNameCollectionInstallmentName() {
        return new Report.Tablix5 .Textbox70 .Textbox28 .Textbox48 .Textbox120 .Textbox56 .Textbox145 .InstallmentNameCollection.InstallmentName();
    }

    /**
     * Create an instance of {@link Report.Tablix5 .WardNameCollection.WardName.Textbox180 }
     * 
     */
    public Report.Tablix5 .WardNameCollection.WardName.Textbox180 createReportTablix5WardNameCollectionWardNameTextbox180() {
        return new Report.Tablix5 .WardNameCollection.WardName.Textbox180();
    }

    /**
     * Create an instance of {@link Report.Tablix5 .Textbox70 .Textbox28 .Textbox48 .Textbox120 .Textbox56 }
     * 
     */
    public Report.Tablix5 .Textbox70 .Textbox28 .Textbox48 .Textbox120 .Textbox56 createReportTablix5Textbox70Textbox28Textbox48Textbox120Textbox56() {
        return new Report.Tablix5 .Textbox70 .Textbox28 .Textbox48 .Textbox120 .Textbox56();
    }

    /**
     * Create an instance of {@link Report.Tablix5 .WardNameCollection.WardName.Textbox114 .Textbox145 }
     * 
     */
    public Report.Tablix5 .WardNameCollection.WardName.Textbox114 .Textbox145 createReportTablix5WardNameCollectionWardNameTextbox114Textbox145() {
        return new Report.Tablix5 .WardNameCollection.WardName.Textbox114 .Textbox145();
    }

    /**
     * Create an instance of {@link Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .Textbox115 .Textbox145 }
     * 
     */
    public Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .Textbox115 .Textbox145 createReportTablix5WardNameCollectionWardNameStreet1CollectionStreet1Textbox115Textbox145() {
        return new Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .Textbox115 .Textbox145();
    }

    /**
     * Create an instance of {@link Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2 .AssesmentNoCollection.AssesmentNo.WUConnectionNo.OwnerFName.NewDoorNo.Textbox145 .InstallmentNameCollection }
     * 
     */
    public Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2 .AssesmentNoCollection.AssesmentNo.WUConnectionNo.OwnerFName.NewDoorNo.Textbox145 .InstallmentNameCollection createReportTablix5WardNameCollectionWardNameStreet1CollectionStreet1BalanceTax2AssesmentNoCollectionAssesmentNoWUConnectionNoOwnerFNameNewDoorNoTextbox145InstallmentNameCollection() {
        return new Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2 .AssesmentNoCollection.AssesmentNo.WUConnectionNo.OwnerFName.NewDoorNo.Textbox145 .InstallmentNameCollection();
    }

    /**
     * Create an instance of {@link Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2 .AssesmentNoCollection.AssesmentNo.WUConnectionNo.OwnerFName.NewDoorNo.Textbox145 .InstallmentNameCollection.InstallmentName }
     * 
     */
    public Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2 .AssesmentNoCollection.AssesmentNo.WUConnectionNo.OwnerFName.NewDoorNo.Textbox145 .InstallmentNameCollection.InstallmentName createReportTablix5WardNameCollectionWardNameStreet1CollectionStreet1BalanceTax2AssesmentNoCollectionAssesmentNoWUConnectionNoOwnerFNameNewDoorNoTextbox145InstallmentNameCollectionInstallmentName() {
        return new Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2 .AssesmentNoCollection.AssesmentNo.WUConnectionNo.OwnerFName.NewDoorNo.Textbox145 .InstallmentNameCollection.InstallmentName();
    }

    /**
     * Create an instance of {@link Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2 .AssesmentNoCollection.AssesmentNo.WUConnectionNo.OwnerFName.NewDoorNo }
     * 
     */
    public Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2 .AssesmentNoCollection.AssesmentNo.WUConnectionNo.OwnerFName.NewDoorNo createReportTablix5WardNameCollectionWardNameStreet1CollectionStreet1BalanceTax2AssesmentNoCollectionAssesmentNoWUConnectionNoOwnerFNameNewDoorNo() {
        return new Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2 .AssesmentNoCollection.AssesmentNo.WUConnectionNo.OwnerFName.NewDoorNo();
    }

    /**
     * Create an instance of {@link Report.Tablix5 }
     * 
     */
    public Report.Tablix5 createReportTablix5() {
        return new Report.Tablix5();
    }

    /**
     * Create an instance of {@link Report.Tablix5 .WardNameCollection.WardName }
     * 
     */
    public Report.Tablix5 .WardNameCollection.WardName createReportTablix5WardNameCollectionWardName() {
        return new Report.Tablix5 .WardNameCollection.WardName();
    }

    /**
     * Create an instance of {@link Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2 .AssesmentNoCollection }
     * 
     */
    public Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2 .AssesmentNoCollection createReportTablix5WardNameCollectionWardNameStreet1CollectionStreet1BalanceTax2AssesmentNoCollection() {
        return new Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .BalanceTax2 .AssesmentNoCollection();
    }

    /**
     * Create an instance of {@link Report.Tablix5 .WardNameCollection.WardName.Textbox180 .Textbox181 .Textbox146 }
     * 
     */
    public Report.Tablix5 .WardNameCollection.WardName.Textbox180 .Textbox181 .Textbox146 createReportTablix5WardNameCollectionWardNameTextbox180Textbox181Textbox146() {
        return new Report.Tablix5 .WardNameCollection.WardName.Textbox180 .Textbox181 .Textbox146();
    }

    /**
     * Create an instance of {@link Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .Textbox115 .Textbox145 .InstallmentNameCollection }
     * 
     */
    public Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .Textbox115 .Textbox145 .InstallmentNameCollection createReportTablix5WardNameCollectionWardNameStreet1CollectionStreet1Textbox115Textbox145InstallmentNameCollection() {
        return new Report.Tablix5 .WardNameCollection.WardName.Street1Collection.Street1 .Textbox115 .Textbox145 .InstallmentNameCollection();
    }

}
